rpm_metadata = [{'path': './tests/assets/rpms/15.6_oss/aarch64/glow-1.5.1-lp156.2.3.1.aarch64.rpm',
  'name': 'glow',
  'epoch': None,
  'version': '1.5.1',
  'release': 'lp156.2.3.1',
  'arch': 'aarch64',
  'sourcerpm': 'glow-1.5.1-lp156.2.3.1.src.rpm',
  'buildtime': 1745995453,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18878/openSUSE_Leap_15.6_Update/701971b638455be15db0a7447a3d41f8-glow.openSUSE_Leap_15.6_Update',
  'license': 'MIT',
  'filesizes': [21563120, 0, 7004, 0, 1080],
  'filemodes': [33261, 16877, 33188, 16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5],
  'dirindexes': [0, 1, 2, 3, 4],
  'basenames': ['glow', 'glow', 'README.md', 'glow', 'LICENSE'],
  'dirnames': ['/usr/bin/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/glow/',
               '/usr/share/licenses/',
               '/usr/share/licenses/glow/']},
 {'path': './tests/assets/rpms/15.6_oss/aarch64/perl-Mail-SPF_XS-0.01-lp156.2.3.1.aarch64.rpm',
  'name': 'perl-Mail-SPF_XS',
  'epoch': None,
  'version': '0.01',
  'release': 'lp156.2.3.1',
  'arch': 'aarch64',
  'sourcerpm': 'libspf2-1.2.11-lp156.2.3.1.src.rpm',
  'buildtime': 1733655479,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18704/openSUSE_Leap_15.6_Update/f96a54c769a87ecdeb68271c05acb317-libspf2.openSUSE_Leap_15.6_Update',
  'license': 'Artistic-1.0 OR GPL-1.0-or-later',
  'filesizes': [0, 946, 0, 0, 67336, 1455],
  'filemodes': [16877, 33188, 16877, 16877, 33261, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5, 6],
  'dirindexes': [0, 1, 2, 3, 4, 5],
  'basenames': ['Mail',
                'SPF_XS.pm',
                'Mail',
                'SPF_XS',
                'SPF_XS.so',
                'Mail::SPF_XS.3pm.gz'],
  'dirnames': ['/usr/lib/perl5/vendor_perl/5.26.1/aarch64-linux-thread-multi/',
               '/usr/lib/perl5/vendor_perl/5.26.1/aarch64-linux-thread-multi/Mail/',
               '/usr/lib/perl5/vendor_perl/5.26.1/aarch64-linux-thread-multi/auto/',
               '/usr/lib/perl5/vendor_perl/5.26.1/aarch64-linux-thread-multi/auto/Mail/',
               '/usr/lib/perl5/vendor_perl/5.26.1/aarch64-linux-thread-multi/auto/Mail/SPF_XS/',
               '/usr/share/man/man3/']},
 {'path': './tests/assets/rpms/15.6_oss/noarch/gtk3-branding-openSUSE-15.0-lp156.4.2.1.noarch.rpm',
  'name': 'gtk3-branding-openSUSE',
  'epoch': None,
  'version': '15.0',
  'release': 'lp156.4.2.1',
  'arch': 'noarch',
  'sourcerpm': 'gtk3-branding-openSUSE-15.0-lp156.4.2.1.src.rpm',
  'buildtime': 1736261123,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18726/openSUSE_Leap_15.6_Update/9c191be4fa5977d7f0b147c7bad967f6-gtk3-branding.openSUSE_Leap_15.6_Update:openSUSE',
  'license': 'BSD-3-Clause',
  'filesizes': [426, 0, 1616],
  'filemodes': [33188, 16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1],
  'fileinodes': [1, 2, 3],
  'dirindexes': [0, 1, 2],
  'basenames': ['settings.ini', 'gtk3-branding-openSUSE', 'COPYING'],
  'dirnames': ['/etc/gtk-3.0/',
               '/usr/share/licenses/',
               '/usr/share/licenses/gtk3-branding-openSUSE/']},
 {'path': './tests/assets/rpms/15.6_oss/noarch/libgarcon-branding-openSUSE-4.18.0+git4.79f6d44-lp156.2.2.16.noarch.rpm',
  'name': 'libgarcon-branding-openSUSE',
  'epoch': None,
  'version': '4.18.0+git4.79f6d44',
  'release': 'lp156.2.2.16',
  'arch': 'noarch',
  'sourcerpm': 'xfce4-branding-openSUSE-4.18.0+git4.79f6d44-lp156.2.2.16.src.rpm',
  'buildtime': 1732806717,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18604/openSUSE_Leap_15.6_Update/3f041d469efe697d26a27aa7270b8dbd-xfce4-branding-openSUSE.openSUSE_Leap_15.6_Update',
  'license': 'CC-BY-SA-3.0 AND GPL-2.0-only',
  'filesizes': [0, 5098, 0, 99, 0, 18092],
  'filemodes': [16877, 33188, 16877, 33188, 16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5, 6],
  'dirindexes': [0, 1, 2, 3, 4, 5],
  'basenames': ['menus',
                'xfce-applications.menu',
                'desktop-directories',
                'YaST.directory',
                'libgarcon-branding-openSUSE',
                'COPYING'],
  'dirnames': ['/etc/xdg/',
               '/etc/xdg/menus/',
               '/usr/share/',
               '/usr/share/desktop-directories/',
               '/usr/share/licenses/',
               '/usr/share/licenses/libgarcon-branding-openSUSE/']},
 {'path': './tests/assets/rpms/15.6_oss/ppc64le/glow-1.5.1-lp156.2.3.1.ppc64le.rpm',
  'name': 'glow',
  'epoch': None,
  'version': '1.5.1',
  'release': 'lp156.2.3.1',
  'arch': 'ppc64le',
  'sourcerpm': 'glow-1.5.1-lp156.2.3.1.src.rpm',
  'buildtime': 1745995448,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18878/openSUSE_Leap_15.6_Update/701971b638455be15db0a7447a3d41f8-glow.openSUSE_Leap_15.6_Update',
  'license': 'MIT',
  'filesizes': [22742704, 0, 7004, 0, 1080],
  'filemodes': [33261, 16877, 33188, 16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5],
  'dirindexes': [0, 1, 2, 3, 4],
  'basenames': ['glow', 'glow', 'README.md', 'glow', 'LICENSE'],
  'dirnames': ['/usr/bin/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/glow/',
               '/usr/share/licenses/',
               '/usr/share/licenses/glow/']},
 {'path': './tests/assets/rpms/15.6_oss/ppc64le/libspf2-2-1.2.11-lp156.2.3.1.ppc64le.rpm',
  'name': 'libspf2-2',
  'epoch': None,
  'version': '1.2.11',
  'release': 'lp156.2.3.1',
  'arch': 'ppc64le',
  'sourcerpm': 'libspf2-1.2.11-lp156.2.3.1.src.rpm',
  'buildtime': 1733655793,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18704/openSUSE_Leap_15.6_Update/f96a54c769a87ecdeb68271c05acb317-libspf2.openSUSE_Leap_15.6_Update',
  'license': 'BSD-2-Clause OR LGPL-2.1-or-later',
  'filesizes': [16, 198600, 0, 4302, 5927, 0, 28619],
  'filemodes': [41471, 33261, 16877, 33188, 33188, 16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5, 6, 7],
  'dirindexes': [0, 0, 1, 2, 2, 3, 4],
  'basenames': ['libspf2.so.2',
                'libspf2.so.2.1.0',
                'libspf2-2',
                'README',
                'TODO',
                'libspf2-2',
                'LICENSES'],
  'dirnames': ['/usr/lib64/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/libspf2-2/',
               '/usr/share/licenses/',
               '/usr/share/licenses/libspf2-2/']},
 {'path': './tests/assets/rpms/15.6_oss/s390x/glow-1.5.1-lp156.2.3.1.s390x.rpm',
  'name': 'glow',
  'epoch': None,
  'version': '1.5.1',
  'release': 'lp156.2.3.1',
  'arch': 's390x',
  'sourcerpm': 'glow-1.5.1-lp156.2.3.1.src.rpm',
  'buildtime': 1745995476,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18878/openSUSE_Leap_15.6_Update/701971b638455be15db0a7447a3d41f8-glow.openSUSE_Leap_15.6_Update',
  'license': 'MIT',
  'filesizes': [24377200, 0, 7004, 0, 1080],
  'filemodes': [33261, 16877, 33188, 16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5],
  'dirindexes': [0, 1, 2, 3, 4],
  'basenames': ['glow', 'glow', 'README.md', 'glow', 'LICENSE'],
  'dirnames': ['/usr/bin/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/glow/',
               '/usr/share/licenses/',
               '/usr/share/licenses/glow/']},
 {'path': './tests/assets/rpms/15.6_oss/s390x/patterns-base-apparmor-20200505-lp156.17.3.1.s390x.rpm',
  'name': 'patterns-base-apparmor',
  'epoch': None,
  'version': '20200505',
  'release': 'lp156.17.3.1',
  'arch': 's390x',
  'sourcerpm': 'patterns-base-20200505-lp156.17.3.1.src.rpm',
  'buildtime': 1720520062,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18462/openSUSE_Leap_15.6_Update/9c2a496c551ea1decd821f9ba3a5ea14-patterns-base.openSUSE_Leap_15.6_Update',
  'license': 'MIT',
  'filesizes': [0, 54],
  'filemodes': [16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1],
  'fileinodes': [1, 2],
  'dirindexes': [0, 1],
  'basenames': ['patterns', 'apparmor.txt'],
  'dirnames': ['/usr/share/doc/packages/',
               '/usr/share/doc/packages/patterns/']},
 {'path': './tests/assets/rpms/15.6_oss/s390x/patterns-base-apparmor-32bit-20200505-lp156.17.3.1.s390x.rpm',
  'name': 'patterns-base-apparmor-32bit',
  'epoch': None,
  'version': '20200505',
  'release': 'lp156.17.3.1',
  'arch': 's390x',
  'sourcerpm': 'patterns-base-20200505-lp156.17.3.1.src.rpm',
  'buildtime': 1720520062,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18462/openSUSE_Leap_15.6_Update/9c2a496c551ea1decd821f9ba3a5ea14-patterns-base.openSUSE_Leap_15.6_Update',
  'license': 'MIT',
  'filesizes': [0, 54],
  'filemodes': [16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1],
  'fileinodes': [1, 2],
  'dirindexes': [0, 1],
  'basenames': ['patterns', 'apparmor-32bit.txt'],
  'dirnames': ['/usr/share/doc/packages/',
               '/usr/share/doc/packages/patterns/']},
 {'path': './tests/assets/rpms/15.6_oss/s390x/upx-5.0.0-lp156.3.3.1.s390x.rpm',
  'name': 'upx',
  'epoch': None,
  'version': '5.0.0',
  'release': 'lp156.3.3.1',
  'arch': 's390x',
  'sourcerpm': 'upx-5.0.0-lp156.3.3.1.src.rpm',
  'buildtime': 1744547534,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18862/openSUSE_Leap_15.6_Update/23e8d7a56d426835465275907fe2b6ef-upx.openSUSE_Leap_15.6_Update',
  'license': 'Apache-2.0 WITH LLVM-exception AND GPL-2.0-or-later AND '
             'BSD-4-Clause AND BSD-3-Clause AND MIT AND Zlib AND (CPL-1.0 OR '
             'LGPL-2.1-only)',
  'filesizes': [2726720,
                0,
                18092,
                5448,
                25618,
                3728,
                2296,
                38597,
                37208,
                0,
                5448,
                12257],
  'filemodes': [33261,
                16877,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                16877,
                33188,
                33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'dirindexes': [0, 1, 2, 2, 2, 2, 2, 2, 2, 3, 4, 5],
  'basenames': ['upx',
                'upx',
                'COPYING',
                'LICENSE',
                'NEWS',
                'README',
                'THANKS.txt',
                'upx-doc.html',
                'upx-doc.txt',
                'upx',
                'LICENSE',
                'upx.1.gz'],
  'dirnames': ['/usr/bin/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/upx/',
               '/usr/share/licenses/',
               '/usr/share/licenses/upx/',
               '/usr/share/man/man1/']},
 {'path': './tests/assets/rpms/15.6_oss/x86_64/glow-1.5.1-lp156.2.3.1.x86_64.rpm',
  'name': 'glow',
  'epoch': None,
  'version': '1.5.1',
  'release': 'lp156.2.3.1',
  'arch': 'x86_64',
  'sourcerpm': 'glow-1.5.1-lp156.2.3.1.src.rpm',
  'buildtime': 1745995410,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18878/openSUSE_Leap_15.6_Update/701971b638455be15db0a7447a3d41f8-glow.openSUSE_Leap_15.6_Update',
  'license': 'MIT',
  'filesizes': [22673000, 0, 7004, 0, 1080],
  'filemodes': [33261, 16877, 33188, 16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5],
  'dirindexes': [0, 1, 2, 3, 4],
  'basenames': ['glow', 'glow', 'README.md', 'glow', 'LICENSE'],
  'dirnames': ['/usr/bin/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/glow/',
               '/usr/share/licenses/',
               '/usr/share/licenses/glow/']},
 {'path': './tests/assets/rpms/15.6_oss/x86_64/libspf2-2-1.2.11-lp156.2.3.1.x86_64.rpm',
  'name': 'libspf2-2',
  'epoch': None,
  'version': '1.2.11',
  'release': 'lp156.2.3.1',
  'arch': 'x86_64',
  'sourcerpm': 'libspf2-1.2.11-lp156.2.3.1.src.rpm',
  'buildtime': 1733655452,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18704/openSUSE_Leap_15.6_Update/f96a54c769a87ecdeb68271c05acb317-libspf2.openSUSE_Leap_15.6_Update',
  'license': 'BSD-2-Clause OR LGPL-2.1-or-later',
  'filesizes': [16, 112656, 0, 4302, 5927, 0, 28619],
  'filemodes': [41471, 33261, 16877, 33188, 33188, 16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1, 1, 1, 1, 1, 1],
  'fileinodes': [1, 2, 3, 4, 5, 6, 7],
  'dirindexes': [0, 0, 1, 2, 2, 3, 4],
  'basenames': ['libspf2.so.2',
                'libspf2.so.2.1.0',
                'libspf2-2',
                'README',
                'TODO',
                'libspf2-2',
                'LICENSES'],
  'dirnames': ['/usr/lib64/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/libspf2-2/',
               '/usr/share/licenses/',
               '/usr/share/licenses/libspf2-2/']},
 {'path': './tests/assets/rpms/15.6_oss/x86_64/patterns-base-apparmor-20200505-lp156.17.3.1.x86_64.rpm',
  'name': 'patterns-base-apparmor',
  'epoch': None,
  'version': '20200505',
  'release': 'lp156.17.3.1',
  'arch': 'x86_64',
  'sourcerpm': 'patterns-base-20200505-lp156.17.3.1.src.rpm',
  'buildtime': 1720520048,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18462/openSUSE_Leap_15.6_Update/9c2a496c551ea1decd821f9ba3a5ea14-patterns-base.openSUSE_Leap_15.6_Update',
  'license': 'MIT',
  'filesizes': [0, 54],
  'filemodes': [16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1],
  'fileinodes': [1, 2],
  'dirindexes': [0, 1],
  'basenames': ['patterns', 'apparmor.txt'],
  'dirnames': ['/usr/share/doc/packages/',
               '/usr/share/doc/packages/patterns/']},
 {'path': './tests/assets/rpms/15.6_oss/x86_64/patterns-base-apparmor-32bit-20200505-lp156.17.3.1.x86_64.rpm',
  'name': 'patterns-base-apparmor-32bit',
  'epoch': None,
  'version': '20200505',
  'release': 'lp156.17.3.1',
  'arch': 'x86_64',
  'sourcerpm': 'patterns-base-20200505-lp156.17.3.1.src.rpm',
  'buildtime': 1720520048,
  'disturl': 'obs://build.opensuse.org/openSUSE:Maintenance:18462/openSUSE_Leap_15.6_Update/9c2a496c551ea1decd821f9ba3a5ea14-patterns-base.openSUSE_Leap_15.6_Update',
  'license': 'MIT',
  'filesizes': [0, 54],
  'filemodes': [16877, 33188],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1, 1],
  'fileinodes': [1, 2],
  'dirindexes': [0, 1],
  'basenames': ['patterns', 'apparmor-32bit.txt'],
  'dirnames': ['/usr/share/doc/packages/',
               '/usr/share/doc/packages/patterns/']},
 {'path': './tests/assets/rpms/15.6_oss/x86_64/zypper-1.14.71-150600.8.1.x86_64.rpm',
  'name': 'zypper',
  'epoch': None,
  'version': '1.14.71',
  'release': '150600.8.1',
  'arch': 'x86_64',
  'sourcerpm': 'zypper-1.14.71-150600.8.1.src.rpm',
  'buildtime': 1714054344,
  'disturl': 'obs://build.suse.de/SUSE:SLE-15-SP6:GA/standard/530ca4e15e44dd1555e82d3a5ac31e75-zypper',
  'license': 'GPL-2.0-or-later',
  'filesizes': [139,
                134,
                8384,
                754,
                6,
                3423352,
                0,
                0,
                31048,
                4742,
                0,
                110,
                0,
                1163,
                200370,
                43440,
                32010,
                2783,
                2821,
                167694,
                170119,
                150894,
                172539,
                138232,
                9028,
                169856,
                11215,
                352,
                157617,
                172402,
                68691,
                2732,
                742,
                3726,
                10714,
                159711,
                156726,
                169256,
                190263,
                108759,
                156444,
                114627,
                13203,
                6133,
                71954,
                170794,
                100964,
                13949,
                161878,
                158010,
                166569,
                65278,
                216307,
                173149,
                7058,
                1203,
                163661,
                2953,
                67418,
                153502,
                219044,
                1389,
                147573,
                148475,
                580,
                33572,
                0,
                0,
                9055,
                2777,
                0],
  'filemodes': [33188,
                33188,
                33188,
                33261,
                41471,
                33261,
                16877,
                16877,
                33261,
                33188,
                16877,
                33188,
                16877,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                16877,
                16877,
                33188,
                33188,
                33184],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1],
  'fileinodes': [1,
                 2,
                 3,
                 4,
                 5,
                 6,
                 7,
                 8,
                 9,
                 10,
                 11,
                 12,
                 13,
                 14,
                 15,
                 16,
                 17,
                 18,
                 19,
                 20,
                 21,
                 22,
                 23,
                 24,
                 25,
                 26,
                 27,
                 28,
                 29,
                 30,
                 31,
                 32,
                 33,
                 34,
                 35,
                 36,
                 37,
                 38,
                 39,
                 40,
                 41,
                 42,
                 43,
                 44,
                 45,
                 46,
                 47,
                 48,
                 49,
                 50,
                 51,
                 52,
                 53,
                 54,
                 55,
                 56,
                 57,
                 58,
                 59,
                 60,
                 61,
                 62,
                 63,
                 64,
                 65,
                 66,
                 67,
                 68,
                 69,
                 70,
                 71],
  'dirindexes': [0,
                 0,
                 1,
                 2,
                 2,
                 2,
                 3,
                 4,
                 5,
                 6,
                 7,
                 8,
                 9,
                 10,
                 11,
                 12,
                 13,
                 14,
                 15,
                 16,
                 17,
                 18,
                 19,
                 20,
                 21,
                 22,
                 23,
                 24,
                 25,
                 26,
                 27,
                 28,
                 29,
                 30,
                 31,
                 32,
                 33,
                 34,
                 35,
                 36,
                 37,
                 38,
                 39,
                 40,
                 41,
                 42,
                 43,
                 44,
                 45,
                 46,
                 47,
                 48,
                 49,
                 50,
                 51,
                 52,
                 53,
                 54,
                 55,
                 56,
                 57,
                 58,
                 59,
                 60,
                 61,
                 61,
                 62,
                 63,
                 64,
                 63,
                 65],
  'basenames': ['zypp-refresh.lr',
                'zypper.lr',
                'zypper.conf',
                'installation_sources',
                'yzpper',
                'zypper',
                'zypper',
                'commands',
                'zypp-refresh',
                'zypper',
                'zypper',
                'HACKING',
                'zypper',
                'COPYING',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypp-refresh.8.gz',
                'zypper.8.gz',
                'zypper',
                'xml',
                'xmlout.rnc',
                'zypper.aug',
                'zypper.log'],
  'dirnames': ['/etc/logrotate.d/',
               '/etc/zypp/',
               '/usr/bin/',
               '/usr/lib/',
               '/usr/lib/zypper/',
               '/usr/sbin/',
               '/usr/share/bash-completion/completions/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/zypper/',
               '/usr/share/licenses/',
               '/usr/share/licenses/zypper/',
               '/usr/share/locale/ar/LC_MESSAGES/',
               '/usr/share/locale/ast/LC_MESSAGES/',
               '/usr/share/locale/be/LC_MESSAGES/',
               '/usr/share/locale/bg/LC_MESSAGES/',
               '/usr/share/locale/bn/LC_MESSAGES/',
               '/usr/share/locale/ca/LC_MESSAGES/',
               '/usr/share/locale/cs/LC_MESSAGES/',
               '/usr/share/locale/da/LC_MESSAGES/',
               '/usr/share/locale/de/LC_MESSAGES/',
               '/usr/share/locale/el/LC_MESSAGES/',
               '/usr/share/locale/en_GB/LC_MESSAGES/',
               '/usr/share/locale/es/LC_MESSAGES/',
               '/usr/share/locale/et/LC_MESSAGES/',
               '/usr/share/locale/fa/LC_MESSAGES/',
               '/usr/share/locale/fi/LC_MESSAGES/',
               '/usr/share/locale/fr/LC_MESSAGES/',
               '/usr/share/locale/gl/LC_MESSAGES/',
               '/usr/share/locale/gu/LC_MESSAGES/',
               '/usr/share/locale/he/LC_MESSAGES/',
               '/usr/share/locale/hi/LC_MESSAGES/',
               '/usr/share/locale/hr/LC_MESSAGES/',
               '/usr/share/locale/hu/LC_MESSAGES/',
               '/usr/share/locale/id/LC_MESSAGES/',
               '/usr/share/locale/it/LC_MESSAGES/',
               '/usr/share/locale/ja/LC_MESSAGES/',
               '/usr/share/locale/km/LC_MESSAGES/',
               '/usr/share/locale/ko/LC_MESSAGES/',
               '/usr/share/locale/lt/LC_MESSAGES/',
               '/usr/share/locale/mk/LC_MESSAGES/',
               '/usr/share/locale/mr/LC_MESSAGES/',
               '/usr/share/locale/nb/LC_MESSAGES/',
               '/usr/share/locale/nl/LC_MESSAGES/',
               '/usr/share/locale/nn/LC_MESSAGES/',
               '/usr/share/locale/pa/LC_MESSAGES/',
               '/usr/share/locale/pl/LC_MESSAGES/',
               '/usr/share/locale/pt/LC_MESSAGES/',
               '/usr/share/locale/pt_BR/LC_MESSAGES/',
               '/usr/share/locale/ro/LC_MESSAGES/',
               '/usr/share/locale/ru/LC_MESSAGES/',
               '/usr/share/locale/sk/LC_MESSAGES/',
               '/usr/share/locale/sl/LC_MESSAGES/',
               '/usr/share/locale/sr/LC_MESSAGES/',
               '/usr/share/locale/sv/LC_MESSAGES/',
               '/usr/share/locale/ta/LC_MESSAGES/',
               '/usr/share/locale/th/LC_MESSAGES/',
               '/usr/share/locale/tr/LC_MESSAGES/',
               '/usr/share/locale/uk/LC_MESSAGES/',
               '/usr/share/locale/wa/LC_MESSAGES/',
               '/usr/share/locale/zh_CN/LC_MESSAGES/',
               '/usr/share/locale/zh_TW/LC_MESSAGES/',
               '/usr/share/man/man8/',
               '/usr/share/',
               '/usr/share/zypper/',
               '/usr/share/zypper/xml/',
               '/var/log/']},
 {'path': './tests/assets/rpms/15.6_oss/x86_64/zypper-1.14.71-150600.8.2.x86_64.rpm',
  'name': 'zypper',
  'epoch': None,
  'version': '1.14.71',
  'release': '150600.8.2',
  'arch': 'x86_64',
  'sourcerpm': 'zypper-1.14.71-150600.8.2.src.rpm',
  'buildtime': 1715266079,
  'disturl': 'obs://build.suse.de/SUSE:SLE-15-SP6:GA/standard/530ca4e15e44dd1555e82d3a5ac31e75-zypper',
  'license': 'GPL-2.0-or-later',
  'filesizes': [139,
                134,
                8384,
                754,
                6,
                3423352,
                0,
                0,
                31048,
                4742,
                0,
                110,
                0,
                1163,
                200370,
                43440,
                32010,
                2783,
                2821,
                167694,
                170119,
                150894,
                172539,
                138232,
                9028,
                169856,
                11215,
                352,
                157617,
                172402,
                68691,
                2732,
                742,
                3726,
                10714,
                159711,
                156726,
                169256,
                190263,
                108759,
                156444,
                114627,
                13203,
                6133,
                71954,
                170794,
                100964,
                13949,
                161878,
                158010,
                166569,
                65278,
                216307,
                173149,
                7058,
                1203,
                163661,
                2953,
                67418,
                153502,
                219044,
                1389,
                147573,
                148475,
                580,
                33572,
                0,
                0,
                9055,
                2777,
                0],
  'filemodes': [33188,
                33188,
                33188,
                33261,
                41471,
                33261,
                16877,
                16877,
                33261,
                33188,
                16877,
                33188,
                16877,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                16877,
                16877,
                33188,
                33188,
                33184],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1],
  'fileinodes': [1,
                 2,
                 3,
                 4,
                 5,
                 6,
                 7,
                 8,
                 9,
                 10,
                 11,
                 12,
                 13,
                 14,
                 15,
                 16,
                 17,
                 18,
                 19,
                 20,
                 21,
                 22,
                 23,
                 24,
                 25,
                 26,
                 27,
                 28,
                 29,
                 30,
                 31,
                 32,
                 33,
                 34,
                 35,
                 36,
                 37,
                 38,
                 39,
                 40,
                 41,
                 42,
                 43,
                 44,
                 45,
                 46,
                 47,
                 48,
                 49,
                 50,
                 51,
                 52,
                 53,
                 54,
                 55,
                 56,
                 57,
                 58,
                 59,
                 60,
                 61,
                 62,
                 63,
                 64,
                 65,
                 66,
                 67,
                 68,
                 69,
                 70,
                 71],
  'dirindexes': [0,
                 0,
                 1,
                 2,
                 2,
                 2,
                 3,
                 4,
                 5,
                 6,
                 7,
                 8,
                 9,
                 10,
                 11,
                 12,
                 13,
                 14,
                 15,
                 16,
                 17,
                 18,
                 19,
                 20,
                 21,
                 22,
                 23,
                 24,
                 25,
                 26,
                 27,
                 28,
                 29,
                 30,
                 31,
                 32,
                 33,
                 34,
                 35,
                 36,
                 37,
                 38,
                 39,
                 40,
                 41,
                 42,
                 43,
                 44,
                 45,
                 46,
                 47,
                 48,
                 49,
                 50,
                 51,
                 52,
                 53,
                 54,
                 55,
                 56,
                 57,
                 58,
                 59,
                 60,
                 61,
                 61,
                 62,
                 63,
                 64,
                 63,
                 65],
  'basenames': ['zypp-refresh.lr',
                'zypper.lr',
                'zypper.conf',
                'installation_sources',
                'yzpper',
                'zypper',
                'zypper',
                'commands',
                'zypp-refresh',
                'zypper',
                'zypper',
                'HACKING',
                'zypper',
                'COPYING',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypp-refresh.8.gz',
                'zypper.8.gz',
                'zypper',
                'xml',
                'xmlout.rnc',
                'zypper.aug',
                'zypper.log'],
  'dirnames': ['/etc/logrotate.d/',
               '/etc/zypp/',
               '/usr/bin/',
               '/usr/lib/',
               '/usr/lib/zypper/',
               '/usr/sbin/',
               '/usr/share/bash-completion/completions/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/zypper/',
               '/usr/share/licenses/',
               '/usr/share/licenses/zypper/',
               '/usr/share/locale/ar/LC_MESSAGES/',
               '/usr/share/locale/ast/LC_MESSAGES/',
               '/usr/share/locale/be/LC_MESSAGES/',
               '/usr/share/locale/bg/LC_MESSAGES/',
               '/usr/share/locale/bn/LC_MESSAGES/',
               '/usr/share/locale/ca/LC_MESSAGES/',
               '/usr/share/locale/cs/LC_MESSAGES/',
               '/usr/share/locale/da/LC_MESSAGES/',
               '/usr/share/locale/de/LC_MESSAGES/',
               '/usr/share/locale/el/LC_MESSAGES/',
               '/usr/share/locale/en_GB/LC_MESSAGES/',
               '/usr/share/locale/es/LC_MESSAGES/',
               '/usr/share/locale/et/LC_MESSAGES/',
               '/usr/share/locale/fa/LC_MESSAGES/',
               '/usr/share/locale/fi/LC_MESSAGES/',
               '/usr/share/locale/fr/LC_MESSAGES/',
               '/usr/share/locale/gl/LC_MESSAGES/',
               '/usr/share/locale/gu/LC_MESSAGES/',
               '/usr/share/locale/he/LC_MESSAGES/',
               '/usr/share/locale/hi/LC_MESSAGES/',
               '/usr/share/locale/hr/LC_MESSAGES/',
               '/usr/share/locale/hu/LC_MESSAGES/',
               '/usr/share/locale/id/LC_MESSAGES/',
               '/usr/share/locale/it/LC_MESSAGES/',
               '/usr/share/locale/ja/LC_MESSAGES/',
               '/usr/share/locale/km/LC_MESSAGES/',
               '/usr/share/locale/ko/LC_MESSAGES/',
               '/usr/share/locale/lt/LC_MESSAGES/',
               '/usr/share/locale/mk/LC_MESSAGES/',
               '/usr/share/locale/mr/LC_MESSAGES/',
               '/usr/share/locale/nb/LC_MESSAGES/',
               '/usr/share/locale/nl/LC_MESSAGES/',
               '/usr/share/locale/nn/LC_MESSAGES/',
               '/usr/share/locale/pa/LC_MESSAGES/',
               '/usr/share/locale/pl/LC_MESSAGES/',
               '/usr/share/locale/pt/LC_MESSAGES/',
               '/usr/share/locale/pt_BR/LC_MESSAGES/',
               '/usr/share/locale/ro/LC_MESSAGES/',
               '/usr/share/locale/ru/LC_MESSAGES/',
               '/usr/share/locale/sk/LC_MESSAGES/',
               '/usr/share/locale/sl/LC_MESSAGES/',
               '/usr/share/locale/sr/LC_MESSAGES/',
               '/usr/share/locale/sv/LC_MESSAGES/',
               '/usr/share/locale/ta/LC_MESSAGES/',
               '/usr/share/locale/th/LC_MESSAGES/',
               '/usr/share/locale/tr/LC_MESSAGES/',
               '/usr/share/locale/uk/LC_MESSAGES/',
               '/usr/share/locale/wa/LC_MESSAGES/',
               '/usr/share/locale/zh_CN/LC_MESSAGES/',
               '/usr/share/locale/zh_TW/LC_MESSAGES/',
               '/usr/share/man/man8/',
               '/usr/share/',
               '/usr/share/zypper/',
               '/usr/share/zypper/xml/',
               '/var/log/']},
 {'path': './tests/assets/rpms/15.6_oss/x86_64/zypper-1.14.89-1.1.x86_64.rpm',
  'name': 'zypper',
  'epoch': None,
  'version': '1.14.89',
  'release': '1.1',
  'arch': 'x86_64',
  'sourcerpm': 'zypper-1.14.89-1.1.src.rpm',
  'buildtime': 1746010594,
  'disturl': 'obs://build.opensuse.org/openSUSE:Factory/standard/7a1206db71310709011affc0fc27c153-zypper',
  'license': 'GPL-2.0-or-later',
  'filesizes': [8406,
                754,
                6,
                2460808,
                139,
                134,
                0,
                0,
                35120,
                4742,
                0,
                110,
                0,
                1163,
                2099,
                199630,
                43228,
                32694,
                2783,
                2908,
                727,
                171277,
                170997,
                665,
                150280,
                176289,
                137631,
                8874,
                7410,
                175609,
                11294,
                352,
                165273,
                177991,
                68390,
                2814,
                742,
                3829,
                10773,
                161144,
                159076,
                174785,
                194917,
                30557,
                108135,
                156069,
                114250,
                13617,
                6215,
                73384,
                174149,
                100543,
                13739,
                161263,
                157411,
                172124,
                64965,
                225313,
                1418,
                175714,
                175418,
                1203,
                167232,
                3056,
                66895,
                167692,
                218294,
                1389,
                152507,
                153315,
                578,
                34337,
                0,
                0,
                9268,
                2777,
                0],
  'filemodes': [33188,
                33261,
                41471,
                33261,
                33188,
                33188,
                16877,
                16877,
                33261,
                33188,
                16877,
                33188,
                16877,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                33188,
                16877,
                16877,
                33188,
                33188,
                33184],
  'nosource': [],
  'nopatch': [],
  'filedevices': [1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1],
  'fileinodes': [1,
                 2,
                 3,
                 4,
                 5,
                 6,
                 7,
                 8,
                 9,
                 10,
                 11,
                 12,
                 13,
                 14,
                 15,
                 16,
                 17,
                 18,
                 19,
                 20,
                 21,
                 22,
                 23,
                 24,
                 25,
                 26,
                 27,
                 28,
                 29,
                 30,
                 31,
                 32,
                 33,
                 34,
                 35,
                 36,
                 37,
                 38,
                 39,
                 40,
                 41,
                 42,
                 43,
                 44,
                 45,
                 46,
                 47,
                 48,
                 49,
                 50,
                 51,
                 52,
                 53,
                 54,
                 55,
                 56,
                 57,
                 58,
                 59,
                 60,
                 61,
                 62,
                 63,
                 64,
                 65,
                 66,
                 67,
                 68,
                 69,
                 70,
                 71,
                 72,
                 73,
                 74,
                 75,
                 76,
                 77],
  'dirindexes': [0,
                 1,
                 1,
                 1,
                 2,
                 2,
                 3,
                 4,
                 5,
                 6,
                 7,
                 8,
                 9,
                 10,
                 11,
                 12,
                 13,
                 14,
                 15,
                 16,
                 17,
                 18,
                 19,
                 20,
                 21,
                 22,
                 23,
                 24,
                 25,
                 26,
                 27,
                 28,
                 29,
                 30,
                 31,
                 32,
                 33,
                 34,
                 35,
                 36,
                 37,
                 38,
                 39,
                 40,
                 41,
                 42,
                 43,
                 44,
                 45,
                 46,
                 47,
                 48,
                 49,
                 50,
                 51,
                 52,
                 53,
                 54,
                 55,
                 56,
                 57,
                 58,
                 59,
                 60,
                 61,
                 62,
                 63,
                 64,
                 65,
                 66,
                 67,
                 67,
                 68,
                 69,
                 70,
                 69,
                 71],
  'basenames': ['zypper.conf',
                'installation_sources',
                'yzpper',
                'zypper',
                'zypp-refresh.lr',
                'zypper.lr',
                'zypper',
                'commands',
                'zypp-refresh',
                'zypper',
                'zypper',
                'HACKING',
                'zypper',
                'COPYING',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypper.mo',
                'zypp-refresh.8.gz',
                'zypper.8.gz',
                'zypper',
                'xml',
                'xmlout.rnc',
                'zypper.aug',
                'zypper.log'],
  'dirnames': ['/etc/zypp/',
               '/usr/bin/',
               '/usr/etc/logrotate.d/',
               '/usr/lib/',
               '/usr/lib/zypper/',
               '/usr/sbin/',
               '/usr/share/bash-completion/completions/',
               '/usr/share/doc/packages/',
               '/usr/share/doc/packages/zypper/',
               '/usr/share/licenses/',
               '/usr/share/licenses/zypper/',
               '/usr/share/locale/af/LC_MESSAGES/',
               '/usr/share/locale/ar/LC_MESSAGES/',
               '/usr/share/locale/ast/LC_MESSAGES/',
               '/usr/share/locale/be/LC_MESSAGES/',
               '/usr/share/locale/bg/LC_MESSAGES/',
               '/usr/share/locale/bn/LC_MESSAGES/',
               '/usr/share/locale/bs/LC_MESSAGES/',
               '/usr/share/locale/ca/LC_MESSAGES/',
               '/usr/share/locale/cs/LC_MESSAGES/',
               '/usr/share/locale/cy/LC_MESSAGES/',
               '/usr/share/locale/da/LC_MESSAGES/',
               '/usr/share/locale/de/LC_MESSAGES/',
               '/usr/share/locale/el/LC_MESSAGES/',
               '/usr/share/locale/en_GB/LC_MESSAGES/',
               '/usr/share/locale/eo/LC_MESSAGES/',
               '/usr/share/locale/es/LC_MESSAGES/',
               '/usr/share/locale/et/LC_MESSAGES/',
               '/usr/share/locale/fa/LC_MESSAGES/',
               '/usr/share/locale/fi/LC_MESSAGES/',
               '/usr/share/locale/fr/LC_MESSAGES/',
               '/usr/share/locale/gl/LC_MESSAGES/',
               '/usr/share/locale/gu/LC_MESSAGES/',
               '/usr/share/locale/he/LC_MESSAGES/',
               '/usr/share/locale/hi/LC_MESSAGES/',
               '/usr/share/locale/hr/LC_MESSAGES/',
               '/usr/share/locale/hu/LC_MESSAGES/',
               '/usr/share/locale/id/LC_MESSAGES/',
               '/usr/share/locale/it/LC_MESSAGES/',
               '/usr/share/locale/ja/LC_MESSAGES/',
               '/usr/share/locale/ka/LC_MESSAGES/',
               '/usr/share/locale/km/LC_MESSAGES/',
               '/usr/share/locale/ko/LC_MESSAGES/',
               '/usr/share/locale/lt/LC_MESSAGES/',
               '/usr/share/locale/mk/LC_MESSAGES/',
               '/usr/share/locale/mr/LC_MESSAGES/',
               '/usr/share/locale/nb/LC_MESSAGES/',
               '/usr/share/locale/nl/LC_MESSAGES/',
               '/usr/share/locale/nn/LC_MESSAGES/',
               '/usr/share/locale/pa/LC_MESSAGES/',
               '/usr/share/locale/pl/LC_MESSAGES/',
               '/usr/share/locale/pt/LC_MESSAGES/',
               '/usr/share/locale/pt_BR/LC_MESSAGES/',
               '/usr/share/locale/ro/LC_MESSAGES/',
               '/usr/share/locale/ru/LC_MESSAGES/',
               '/usr/share/locale/si/LC_MESSAGES/',
               '/usr/share/locale/sk/LC_MESSAGES/',
               '/usr/share/locale/sl/LC_MESSAGES/',
               '/usr/share/locale/sr/LC_MESSAGES/',
               '/usr/share/locale/sv/LC_MESSAGES/',
               '/usr/share/locale/ta/LC_MESSAGES/',
               '/usr/share/locale/th/LC_MESSAGES/',
               '/usr/share/locale/tr/LC_MESSAGES/',
               '/usr/share/locale/uk/LC_MESSAGES/',
               '/usr/share/locale/wa/LC_MESSAGES/',
               '/usr/share/locale/zh_CN/LC_MESSAGES/',
               '/usr/share/locale/zh_TW/LC_MESSAGES/',
               '/usr/share/man/man8/',
               '/usr/share/',
               '/usr/share/zypper/',
               '/usr/share/zypper/xml/',
               '/var/log/']}]
