
== productcompose build description options

=== minimal version

 product_compose_schema: 0.2
 vendor: I_and_myself
 name: my_product
 version: 1.0
 product-type: module

 architectures: [ x86_64 ]

 packages:
  - my-single-rpm-package

=== build options
==== take_all_available_versions

By default only "the best" version of each rpm is taken.
Use this switch to put all candidates on the medium.
For example for maintenance repositories.

==== ignore_missing_packages

Missing packages lead by default to a build failure.
Use this switch to continue. The missing packages are
still listed in the build log.

==== hide_flavor_in_product_directory_name

The flavor name is by default part of the directory
name of the build result. This can be disabled, 
when each flavor has a different arch list. Otherwise
conflicts can happen.

==== flavors

Flavors can be defined with any name. These can be
used to build multiple media from one build description.

Each flavor may define an own architecture list.

It can also be used to add different package sets.

You need to add a _multibuild file to your sources
to enable the build.

==== unpack

unpack defines the packageset to be used for extracting
the content of the rpm packages directly on the medium.

These rpm packages need to provide these files below

 /usr/lib/skelcd/CD1

Currently it gets only extracted to the first/main medium,
but not on source or debug media.

==== packagesets

The packages list lists rpm names to be put on the medium.

There is usually one master list and in addition there
can be addional optional lists.

The additional lists can be filtered by flavors and/or 
architectures.

The packageset requires at least a packages definition,
but may optionaly also a name, flavors or architectures.

=== Details

==== name

The product name.

==== version

The product version

==== summary

The product name in explaining words. It will be presented to the
user on overview screens

==== product-type

Either 'base' for operation systems or 'module' for any product
depending on any existing installation.

==== architectures

An array of the master architectures to be put into the repository.
This can be used to build a single repository usable for many
hardware architectures.

product composer will automatically fall back to "noarch" packages
if the package is not found natively.

Setting a global architecture list is optional, when architectures
are listed for each flavor.

==== bcntsynctag

Optionaly defines a bcntsynctag for OBS. OBS will sync the build
counter over all packages in same repository and architecture
according to this tag.

==== milestone

Optionaly defines a milestone which will be used by OBS at release
time. This can be used to turn candidate builds into a Beta1 for
example

==== build_options

The build options may be used to change the behaviour of the build
process. The options are described above.

Just add them to enable them, no further arguments are allowed.

==== debug

Configure the handling of debuginfo and debugsource rpms.
Use either

  debug: include

to include them or

  debug: drop

to drop all debug packages or

  debug: split

to create a seperate medium mwith -Debug suffix.

Missing debug packages will always be ignored.

==== packages

The package list. It can contain either simple name or it can
be extended by a >, >=, =, <, <= operator to specify a
specific version constraint.

The syntax for the version is rpm like

 [EPOCH:]VERSION[-RELEASE]

A missing epoch means epoch zero. If the release is missing, it
matches any release.

The package list can be valid globally or limited to specific flavors
or architectures.

==== product_compose_schema

Defines the level of the yaml syntax.
Please expect incompatible changes at any time atm.

This will be used to provide backward compability once
we stabilized.

==== product_directory_name

Can be used to specify a directory or medium name manually.
The default is "name-version".

The directory name will always be suffixed by the architecture
and build number.

==== source

Configure the handling of src or nosrc rpms for the picked binaries.
Use either

  source: include

to include all source packages or

  source: drop

to drop all source packages or

  source: split

to create a seperate medium with -Source suffix.

A missing source package leads to a build failure unless
the ignore_missing_packages built option is used.

==== vendor

Defines the company responsible for the content. Can be for example
openSUSE or SUSE. It is used by the install stack.

==== set_updateinfo_from

Can be set to replace the "from" attribute in updateinfo.xml files with a fixed value.
This is shown as patch provider by zypp stack. Otherwise the value stays, OBS is setting
the packager from _patchinfo file here by default.

==== set_updateinfo_id_prefix

Sets a fixed prefix to all id's of included updateinfo data. It is not adding again
if the prefix exists already.

This can be used to have a common identifier for an update for many products, but
still being able to identify the filtering for a specific product.

==== block_updates_under_embargo

The current default is to include maintenance updates under embargo. This option can
be set to abort when an embargo date is in future.

