= productcomposer
:toc:
:icons:
:numbered:
:website: https://www.geckito.org/

== Goals

A lightweight successor for product builder.

It is used to generate product RPM repositories out of a pool of RPMs.
Unlike product builder, these can also be used to ship maintenance updates.

.Currently it supports:
- processing based on a list of RPM package names.
  product compose is currently not taking care of dependencies.
- providing matching source and/or debug packages for picked RPM packages.
  These can be either included into main repository or prepared via
  extra repositories
- optional filters for architectures, versions and flavors can be defined
- it can provide either just a single RPM of a given name or all of them
- it can post process updateinfo data
- post processing to provide various types of RPM meta data generation

Not yet implemented:
- create bootable iso files

== Design

product composer is supposed to be used only inside of OBS builds atm.
OBS or osc is preparing all binary RPM candidates in local directory 
before starting the build.

== Setup in OBS

You will require OBS 2.11 or later.

.Create a new repository with any name. Either in a new or existing project.
- The product-composer package must be available in any repository
  listed in the path elements.
- All scheduler architectures where packages are taken from must be listed.

Your build description file may have any name, but must have a .productcompose
suffix.

The build type for the repository must be set to

  Type: productcompose

in the build configuration (aka prjconf).

== Special setup for maintenance

Ensure to build your patchinfo builds in a repository where "local" is the first
architecture.

Your productcompose file may provide all versions of each RPM if you enable
"take_all_available_versions" in the build options.

include::build_description.adoc[]

