name: Tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    container: registry.suse.com/bci/python:3.11

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          zypper -n install python311-pydantic python311-pytest \
                            python311-setuptools python311-rpm \
                            python311-PyYAML python311-build \
                            python311-pyflakes python311-flake8

      - name: Run Linting (flake8)
        run: flake8 .

      - name: Fix git ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build Package
        run: pyproject-build

      - name: Run Pytest
        run: pytest -v

      - name: Verify Examples
        run: |
          # --system-site-packages is key here to use the zypper-installed libs
          python3 -m venv venv --system-site-packages
          source venv/bin/activate
          pip install --no-dependencies -e .
          productcomposer verify examples/ftp.productcompose

